image: docker:latest
services:
    - docker:dind

stages:
    - deploy

step-develop:
    stage: deploy
    only:
        - dev
    tags:
        - dev
    script:
        - export
        - sudo docker image prune -f
        - sudo docker-compose -f docker-compose.yml build --build-arg react-dev REACT_APP_BASE_PAGE_URL=${REACT_APP_BASE_PAGE_URL} --build-arg react-dev REACT_APP_CMS_URL=${REACT_APP_CMS_URL} --no-cache
        - sudo docker-compose -f docker-compose.yml up -d
step-production:
    stage: deploy
    only:
        - prod
    tags:
        - prod
    script:
        - sudo docker image prune -f
        - sudo docker-compose -f docker-compose-prod.yml build --no-cache
        - sudo docker-compose -f docker-compose-prod.yml up -d
