image: docker:latest
services:
    - docker:dind

stages:
    - deploy

step-develop:
    stage: deploy
    only:
        - dev
    tags:
        - dev
    script:
        - echo "REACT_APP_BASE_PAGE_URL=$REACT_APP_BASE_PAGE_URL_DEV" >> .env
        - echo "REACT_APP_CMS_URL=$REACT_APP_CMS_URL_DEV" >> .env
        - sudo docker image prune -f
        - sudo docker-compose -f docker-compose.yml build --no-cache
        - sudo docker-compose -f docker-compose.yml up -d
step-production:
    stage: deploy
    only:
        - prod
    tags:
        - prod
    script:
        - echo "REACT_APP_BASE_PAGE_URL=$REACT_APP_BASE_PAGE_URL_PROD" >> .env
        - echo "REACT_APP_CMS_URL=$REACT_APP_CMS_URL_PROD" >> .env
        - echo "REACT_APP_UA_TRACK=$REACT_APP_UA_TRACK" >> .env
        - sudo docker image prune -f
        - sudo docker-compose -f docker-compose-prod.yml build --no-cache
        - sudo docker-compose -f docker-compose-prod.yml up -d
