image: docker:latest
services:
    - docker:dind

stages:
    - deploy

step-develop:
    stage: deploy
    only:
        - dev
    tags:
        - dev
    script:
        - sudo docker image prune -f
        - env
        - REACT_APP_CMS_URL=${REACT_APP_CMS_URL}
        - docker-compose
        - -f
        - docker-compose-prod.yml
        - up
        - -d
step-production:
    stage: deploy
    only:
        - prod
    tags:
        - prod
    script:
        - sudo docker image prune -f
        - sudo docker-compose -f docker-compose-prod.yml build --no-cache
        - sudo docker-compose -f docker-compose-prod.yml up -d
