export const FETCH_ARTICLES_REQUEST = 'FETCH_ARTICLES_REQUEST';
export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS';
export const FETCH_ARTICLES_FAILURE = 'FETCH_ARTICLES_FAILURE';
export const CLEAN_FILTERED_ARTICLES = 'CLEAN_FILTERED_ARTICLES';
export const LOAD_NEW_PAGE = "LOAD_NEW_PAGE";
export const LOAD_EXACT_PAGE = "LOAD_EXACT_PAGE";