export const FETCH_NATIONAL_DATA_REQUEST = 'FETCH_NATIONAL_DATA_REQUEST';
export const FETCH_NATIONAL_DATA_SUCCESS = 'FETCH_NATIONAL_DATA_SUCCESS';
export const FETCH_NATIONAL_DATA_FAILURE = 'FETCH_NATIONAL_DATA_FAILURE';
export const FETCH_NATIONAL_DATA_CLEAN_UP = 'FETCH_NATIONAL_DATA_CLEAN_UP';
