export const FETCH_ARTICLES_NEWS_REQUEST = 'FETCH_ARTICLES_NEWS_REQUEST';
export const FETCH_ARTICLES_NEWS_SUCCESS = 'FETCH_ARTICLES_NEWS_SUCCESS';
export const FETCH_ARTICLES_NEWS_FAILURE = 'FETCH_ARTICLES_NEWS_FAILURE';
export const FETCH_ARTICLES_NEWS_CLEAN_UP = 'FETCH_ARTICLES_NEWS_CLEAN_UP';
export const UPDATE_NEWS_PAGE_START_PARAM = 'UPDATE_NEWS_PAGE_START_PARAM';
